const ActivePools = [
    {
        id: 1,
        tag: "completed",
        logo: "https://res.cloudinary.com/daniel23/image/upload/v1689876698/Blue-norva-logo_rzwgvv.webp",
        tags: ["18/05/2023"],
        projectTitle: "Project 1",
        projectDescription:
            "The Blue Norva Project",
        totalRate: "$100234.45",
        maxAllocation: "$2500",
        access: "Public",
        totalRaised: "0 DAI",
        chain: 10,
        status: "completed",
        dateOfCompletion: "23rd Oct, 2022",
        currentBalance: 21000.00,
        targetBalance: 70000.00,
        SLMAmount: "21000/70000.00 USDC",
        percentage: "100.00%",
        tokenDistribution: "20/05/2023",
        tokenPrice: "1 $BLU = 0.0012 $USDC",
        tokenName: "Blue Norva",
        tokenSymbol: "BLU",
        tokenDecimal: "18",
        tokenAddress: "0xa50B23cDfB2eC7c590e84f403256f67cE6dffB84",
        tokenTotalSupply: "1,000,000,000",
        contract: "0xBdFeF93dB6561284FbD2E32b5e2D596FB1037Db8",
        aboutProject:
            "The Blue Norva Project",
        WhitelistPrice: "$0.001",
        PublicSalePrice: " $0.0012",
        InitialMarketCap: "$167k",
        PresaleStart: "2023-05-16 12:00",
        PresaleEnd: "2023-05-17 12:00",
        Presale: "70,000,000 BLU",
        Website: "www.bluenorva.io",
        Whitepaper: "https://bluenorva.gitbook.io",
        Twitter: "https://twitter.com/bluenorva",
        Discord: " https://discord.gg/ScCDVca7jG",
        minimumPurchase: "100 USDC",
        maximumPurchase: "500 USDC",
        projectBenefits: [
            "1) BlueNorva Staking Game is a new game that revolves around the concept of mining resources from a distant planet called Nova prime.",
            "2) Also, The game revolves around Novaurs extracting a mineral called Aurorium $Aur from the planet using mining rigs, fuel rods. etc. The $Aur tokens can be sold in a C2C market or used to mint fuel rods.",
        ],
        projectName: "Blue Norva",
    },
    {
        id: 2,
        tag: "active",
        logo: "https://res.cloudinary.com/daniel23/image/upload/v1689876015/Astrava_svg_1_xwtmlp.svg",
        tags: ["18/05/2023"],
        projectTitle: "Project 2",
        projectDescription:
            "The Astrava Project",
        totalRate: "$100234.45",
        maxAllocation: "$2500",
        access: "Private",
        totalRaised: "0 DAI",
        chain: 10,
        status: "active",
        dateOfCompletion: "23rd Oct, 2022",
        currentBalance: 87079007.22,
        targetBalance: 87083333.33,
        SLMAmount: "87079007.22/87083333.33 DAI",
        percentage: "100.00%",
        tokenDistribution: "20/05/2023",
        tokenPrice: "1 $AST = 0.01 $USDC",
        tokenName: "ASTRAVA",
        tokenSymbol: "AST",
        tokenDecimal: "18",
        tokenAddress: "0x5c739e44b9066e44830a1B0942Fe322300A620c8",
        tokenTotalSupply: "100,000,000",
        contract: "0xBdFeF93dB6561284FbD2E32b5e2D596FB1037Db8",
        aboutProject:
            "The Astrava  Project",
        WhitelistPrice: "$0.001",
        PublicSalePrice: " $0.0012",
        InitialMarketCap: "$121500",
        PresaleStart: "2023-07-16 12:00",
        PresaleEnd: "2023-07-18 12:00",
        Presale: "20,000,000 AST",
        Website: "www.astrava.xyz/",
        Whitepaper: "https://docs.astrava.xyz/",
        Twitter: "https://twitter.com/astrava_xyz",
        Discord: " https://discord.gg/kE9yvnHtTP",
        minimumPurchase: "200 USDC",
        maximumPurchase: "2000 USDC",
        projectBenefits: [
            "1) 10% Presale : 50% distributed at tge followed by 25% distribution Monthly for two months",
            "2) 5% Liquidity : 100% Released at TGE ",
            "3) 45% Community Reserve and liquidity incentives : 5% at TGE followed by linear vesting for 4 years .",
            "4) 30% Platform incentives : 5% at TGE followed by linear vesting for 5 years ",
            "5) 1% Retroactive Airdrop . User onboarding incentive : 100% distribution at TGE."
        ],
        projectName: "Astrava",
    },

];

const UpcomingPools = [

];

const CompletedPools = [
    {
        id: 1,
        tag: "completed",
        logo: "Logo",
        tags: ["23/11/2023"],
        projectTitle: "Project 3",
        projectDescription:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
        totalRate: "$100234.45",
        maxAllocation: "$2500",
        access: "Public",
        totalRaised: "100234.45 DAI",
        chain: 4002,
        status: "Filled",
        dateOfCompletion: "23rd Oct, 2022",
        currentBalance: 87079007.22,
        targetBalance: 87083333.33,
        SLMAmount: "87079007.22/87083333.33 DAI",
        percentage: "100.00%",
        tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
        tokenPrice: "1 BUSD = 166.66 SLM",
        tokenName: "SoliMax",
        tokenSymbol: "SLM",
        tokenDecimal: "18",
        tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
        tokenTotalSupply: "1,000,000,000",
        aboutProject:
            "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
        projectBenefits: [
            "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
            "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
        ],
        projectName: "MENZY ECOSYSTEM",
    },
    // {
    //   id: 2,
    //   tag: "completed",
    //   logo: "Logo",
    //   tags: ["23/11/2023"],
    //   projectTitle: "Project 3",
    //   projectDescription:
    //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    //   totalRate: "$100234.45",
    //   maxAllocation: "$2500",
    //   access: "Public",
    //   totalRaised: "100234.45 DAI",
    //   chain: 4002,
    //   status: "Filled",
    //   dateOfCompletion: "23rd Oct, 2022",
    //   currentBalance: 87089007.22,
    //   targetBalance: 87083333.33,
    //   SLMAmount: "87079007.22/87083333.33 DAI",
    //   percentage: "100.00%",
    //   tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    //   tokenPrice: "1 BUSD = 166.66 SLM",
    //   tokenName: "SoliMax",
    //   tokenSymbol: "SLM",
    //   tokenDecimal: "18",
    //   tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    //   tokenTotalSupply: "1,000,000,000",
    //   aboutProject:
    //     "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    //   projectBenefits: [
    //     "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
    //     "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    //   ],
    //   projectName: "MENZY ECOSYSTEM",
    // },
    // {
    //   id: 3,
    //   tag: "completed",
    //   logo: "Logo",
    //   tags: ["23/11/2023"],
    //   projectTitle: "Project 3",
    //   projectDescription:
    //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    //   totalRate: "$100234.45",
    //   maxAllocation: "$2500",
    //   access: "Public",
    //   totalRaised: "100234.45 USDT",
    //   chain: 4002,
    //   status: "Filled",
    //   dateOfCompletion: "23rd Oct, 2022",
    //   currentBalance: 87079007.22,
    //   targetBalance: 87083333.33,
    //   SLMAmount: "87079007.22/87083333.33 DAI",
    //   percentage: "100.00%",
    //   tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    //   tokenPrice: "1 BUSD = 166.66 SLM",
    //   tokenName: "SoliMax",
    //   tokenSymbol: "SLM",
    //   tokenDecimal: "18",
    //   tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    //   tokenTotalSupply: "1,000,000,000",
    //   aboutProject:
    //     "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    //   projectBenefits: [
    //     "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
    //     "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    //   ],
    //   projectName: "MENZY ECOSYSTEM",
    // },
];

module.exports = {
    ActivePools,
    UpcomingPools,
    CompletedPools
}